//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int ID { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string OFFICENAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE_1 { get; set; }
        public string PHONE_2 { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string LAT { get; set; }
        public string LNG { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string ARCHIVE { get; set; }
        public string CITY { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
    }
}
