//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrganization()
        {
            this.tblCustomers = new HashSet<tblCustomer>();
            this.tblRoasters = new HashSet<tblRoaster>();
            this.tblTeams = new HashSet<tblTeam>();
            this.tblUserMasters = new HashSet<tblUserMaster>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string CONTACTNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE_1 { get; set; }
        public string PHONE_2 { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string LAT { get; set; }
        public string LNG { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public string ARCHIVE { get; set; }
        public string CITY { get; set; }
        public string IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoaster> tblRoasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeam> tblTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserMaster> tblUserMasters { get; set; }
    }
}
