//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserMaster()
        {
            this.tblUserLogs = new HashSet<tblUserLog>();
            this.tblUserTeams = new HashSet<tblUserTeam>();
        }
    
        public int ID { get; set; }
        public int USERTYPE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string USERSTATUS { get; set; }
        public Nullable<int> USERTEAMID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string USERTOKEN { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string EMAIL { get; set; }
        public string CELLPHONE { get; set; }
        public string WORKINGDAYS { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string EMERGENCYCONTACT { get; set; }
        public string EMERGENCYCONTACTNO { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLog> tblUserLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserTeam> tblUserTeams { get; set; }
    }
}
